#!/bin/bash
# This script will build libhttp_parser.so.
# It will also copy the header files and the library to the current directory
# in a VN conventional way, i.e., ./lib and ./src.
PATH=/usr/bin:/bin:$PATH
LIB_NAME=http-parser
VERSION=2.1
LIB_SO_NAME=libhttp_parser.so
HEADER_TOP_FOLER=include
TARBALL=$LIB_NAME-$VERSION.tar.gz
PACKAGE_DIR=$LIB_NAME
LIB_DIR=lib
UNTAR_ARG='-zxvf'
HOST='arm-linux-'
CC=${HOST}gcc


rm -rf ${LIB_DIR}
rm -rf ${PACKAGE_DIR}
rm -rf ${HEADER_TOP_FOLER}
