################################################################################
#
#
#
# Makefile for the tipster MAC driver
#

obj-$(CONFIG_TIPSTER) += tipster_all.o

tipster_all-objs := tipster.o tipster_dev.o 
