#!/bin/bash
# This script will build expat.
# It will also copy the header files and the library to the current directory
# in a VN conventional way, i.e., ./lib and ./src.
PATH=/usr/bin:/bin:$PATH
APP_NAME=automount
VERSION=3.1.7
SOVERSION=3.1.7
PACKAGE_DIR=autofs-orig
HOST='arm-linux-'
CC=${HOST}gcc

# check if you have the proper gcc
which $CC > /dev/null || exit 1 

#tar $UNTAR_ARG $TARBALL

[ -d "$PACKAGE_DIR" ] || exit 1

cd $PACKAGE_DIR

# configure it for $HOST
#[ -f "Makefile" ] || ./configure --host=$HOST &> /dev/null

# simply make it
make --quiet clean
#cat ../autofs.patch |  patch -R -p 1 > /dev/null 2>&1
cd - > /dev/null

rm -rf ${APP_NAME}

