#!/bin/bash
# This script will install expat. 
PATH=/usr/bin:/bin:$PATH
APP_NAME=lsof
VERSION=4.81.dfsg.1
TARBALL=$APP_NAME-$VERSION.tar.gz
PACKAGE_DIR=$APP_NAME-$VERSION
UNTAR_ARG='-zxvf'
HOST='arm-linux-'
CC=${HOST}gcc

install ${APP_NAME} $1/usr/sbin/

