################################################
# Generated by Code Generator Version 3.0.0.1 #
################################################
MODNAME="buff_mgr"
NodeNum=#BUFMGR_NODE_NUM#

rmmod buff_mgr  > /dev/null 2>&1

#rm /dev/$MODNAME

i=0
while [ "$i" != "$NodeNum" ] 
do
	rm /dev/${MODNAME}$i  > /dev/null 2>&1
	i=$(($i+1))
done

#insmod buff_mgr.ko gsdwMaxReaderNum=4 gsdwNumNodes=$NodeNum
insmod buff_mgr.ko #BUFMGR_ARG#

MAJOR=`cat /proc/devices | grep $MODNAME | sed -e 's/buff_mgr//' | sed -e 's/ //'`

if test -z $MAJOR; then
	echo "The device specified is not found !"
else
	echo "Let's make a node here for $MODNAME with major number $MAJOR"
#	mknod /dev/$MODNAME c $MAJOR 0
	i=0
	while [ "$i" != "$NodeNum" ] 
	do
		mknod /dev/${MODNAME}$i c $MAJOR $i
		i=$(($i+1))
	done
fi
