###############################################
# Generated by Code Generator Version 3.0.0.0 #
###############################################
MODNAME="gpio_i2c"
#rmmod ${MODNAME}  > /dev/null 2>&1

#rm /dev/$MODNAME  > /dev/null 2>&1
#rm /dev/${MODNAME}0  > /dev/null 2>&1
#rm /dev/${MODNAME}1  > /dev/null 2>&1
#rm /dev/${MODNAME}2  > /dev/null 2>&1
#rm /dev/${MODNAME}3  > /dev/null 2>&1

insmod $MODNAME.ko
#insmod $MODNAME.ko iSCL_bus0=0x00000040 iSDA_bus=0x00000080 iSCL_bus1=0x00001000 iSDA_bus1=0x00002000

MAJOR=`cat /proc/devices | grep $MODNAME | sed -e 's/gpio_i2c//' | sed -e 's/ //'`

if test -z $MAJOR; then
	echo "The device specified is not found !"
else
	echo "Let's make a node here for $MODNAME with major number $MAJOR"
	mknod /dev/${MODNAME} c $MAJOR 0
	mknod /dev/${MODNAME}0 c $MAJOR 0
	mknod /dev/${MODNAME}1 c $MAJOR 1
	mknod /dev/${MODNAME}2 c $MAJOR 2
	mknod /dev/${MODNAME}3 c $MAJOR 3
fi
