###############################################
# Generated by Code Generator Version 2.2.0.4 #
###############################################
MODNAME="vpl_tmrc"

#rmmod vpl_tmrc  > /dev/null 2>&1


#rm /dev/${MODNAME}0  > /dev/null 2>&1
#rm /dev/${MODNAME}1   > /dev/null 2>&1 
#rm /dev/${MODNAME}2  > /dev/null 2>&1
#rm /dev/${MODNAME}3  > /dev/null 2>&1

insmod vpl_tmrc.ko

MAJOR=`cat /proc/devices | grep $MODNAME | sed -e 's/vpl_tmrc//' | sed -e 's/ //'`

if test -z $MAJOR; then
	echo "The device specified is not found !"
else
	echo "Let's make a node here for $MODNAME with major number $MAJOR"
	mknod /dev/${MODNAME}0 c $MAJOR 0
	mknod /dev/${MODNAME}1 c $MAJOR 1
	mknod /dev/${MODNAME}2 c $MAJOR 2
	mknod /dev/${MODNAME}3 c $MAJOR 3
fi
