###############################################
# Generated by Code Generator Version 3.0.0.0 #
###############################################
MODNAME="gpio_i2c"
rmmod ${MODNAME}

rm /dev/$MODNAME
rm /dev/${MODNAME}0
rm /dev/${MODNAME}1
rm /dev/${MODNAME}2
rm /dev/${MODNAME}3

cd /home/james.lin/PROJ/Mozart/Audio/GPIO_I2C
insmod $MODNAME.ko

MAJOR=`cat /proc/devices | grep $MODNAME | sed -e 's/gpio_i2c//' | sed -e 's/ //'`

if test -z $MAJOR; then
	echo "The device specified is not found !"
else
	echo "Let's make a node here for $MODNAME with major number $MAJOR"
	mknod /dev/${MODNAME} c $MAJOR 0
	mknod /dev/${MODNAME}0 c $MAJOR 0
	mknod /dev/${MODNAME}1 c $MAJOR 1
	mknod /dev/${MODNAME}2 c $MAJOR 2
	mknod /dev/${MODNAME}3 c $MAJOR 3
fi
