#!/bin/sh
#
# builddeb 1.2
# Copyright 2003 Wichert Akkerman <wichert@wiggy.net>
#
# Simple script to generate a deb package for a Linux kernel. All the
# complexity of what to do with a kernel after it is installer or removed
# is left to other scripts and packages: they can install scripts in the
# /etc/kernel/{pre,post}{inst,rm}.d/ directories that will be called on
# package install and removal.

set -e

# Some variables and settings used throughout the script
version=$KERNELRELEASE
#revision=`cat .version`
tmpdir="$objtree/debian/tmp"
packagename=kilrogg-$version
dpkg_deb="/usr/bin/dpkg-deb"
default_etc_tarball="$objtree/.tmp_rootfs/usr/local/firmware/default_flashfs_files.tar.gz"
# Setup the directory structure
rm -rf "$tmpdir" 
mkdir -p "$tmpdir/DEBIAN" "$tmpdir/tmp" 

# Build and install the kernel
cp -a $ROOTFSIMG "$tmpdir/tmp"
cp -a $default_etc_tarball "$tmpdir/tmp"
# Install the maintainer scripts
for script in postrm preinst prerm ; do
	cat <<EOF > "$tmpdir/DEBIAN/$script"
#!/bin/sh

set -e

exit 0
EOF
	chmod 755 "$tmpdir/DEBIAN/$script"
done

name="Kbuildsomple Compiler <$(id -nu)@$(hostname -f)>"
# Generate potinst file
cat <<EOF > "$tmpdir/DEBIAN/postinst"
#!/bin/sh
PATH=/bin:/sbin:/usr/bin:/usr/sbin
FLASH_PATH="/mnt/flash"
FILE="/tmp/default_flashfs_files.tar.gz"
/usr/sbin/stopallproc
if mountpoint /etc
then
    umount /etc
fi
cd \$FLASH_PATH
rm -rf \$FLASH_PATH/etc/*
tar -zxf \$FILE
sync

ROOTFS_SIZE="0x800000"
MTD_DEBUG=/usr/bin/mtd_debug
NEW_ROOTFS_SIZE=\`stat -c %s /tmp/rootfs.sqfs\`

echo "erase partition 2, size is \$ROOTFS_SIZE"
\$MTD_DEBUG erase /dev/mtd2 0 \$ROOTFS_SIZE
echo "write to flash"
\$MTD_DEBUG write /dev/mtd2 0 \$NEW_ROOTFS_SIZE /tmp/rootfs.sqfs
EOF
chmod 755 "$tmpdir/DEBIAN/postinst"

# Generate a simple changelog template
cat <<EOF > debian/changelog
Kbuildsample ($version-$revision) unstable; urgency=low

  * A standard release

 -- $name  $(date -R)
EOF

# Generate a control file
cat <<EOF > $tmpdir/DEBIAN/control
Section: base
Priority: optional
Maintainer: $name
Package: $packagename
Architecture: any
Description: Kbuild Example, version $version
 This package contains the Kbuildsample, applications and corresponding libraries. 
Version: $version
EOF

# Fix some ownership and permissions
#chown -R root:root "$tmpdir"
#chmod -R go-w "$tmpdir"

# Perform the final magic
$dpkg_deb -b $tmpdir $packagename.deb
#dpkg-gencontrol -isp -p$packagename
#dpkg --build "$tmpdir" ..

exit 0

