#!/bin/bash

PATH=/usr/bin:/bin:$PATH
MOD_ROOT=$PWD
TARGET_ROOT=`readlink -f $1`
MAX_STREAM_NUM=3
STREAM_SERVER_CONF="serverpush_conf.xml"
VIDEO_TRACK_STR=""
TMP_FILE="serverpush.tmp"
#echo "Rtsp Stream Conf generate....MOD_ROOT="$MOD_ROOT
VIDEO_SERVER=0
if cat $TARGET_ROOT/../.config | grep -n "CONFIG_VIDEO_SERVER=y"  > /dev/null  2>&1;then

    VIDEO_SERVER=1
fi






MAX_STREAM_NUM=`cat $TARGET_ROOT/../.config |  grep CONFIG_MAXVIDEOSTREAMNUM | cut -d'=' -f 2`
#echo "RTSP MAX_STREAM_NUM="$MAX_STREAM_NUM
MAX_VIDEO_CHANNEL_NUM=`cat $TARGET_ROOT/../.config |  grep CONFIG_MAXVIDEOCHANNELNUM | cut -d'=' -f 2`
#echo "RTSP MAX_VIDEO_CHANNEL_NUM="$MAX_VIDEO_CHANNEL_NUM

cat $MOD_ROOT/$STREAM_SERVER_CONF >  $TARGET_ROOT/etc/conf.d/serverpush_conf.xml

VIDEO_TRACK_STR="\\n\\t<httpfdipcsock>\/tmp\/serverpush\/http_spush.sck<\/httpfdipcsock>\\n\\t"
VIDEO_TRACK_STR=$VIDEO_TRACK_STR"<boundary>myboundary<\/boundary>\\n\\t"
VIDEO_TRACK_STR=$VIDEO_TRACK_STR"<tracknum>$((MAX_STREAM_NUM*MAX_VIDEO_CHANNEL_NUM))<\/tracknum>\\n\\t"

if [ -e $TMP_FILE ];then

rm -f $TMP_FILE

fi
for (( k=0; k<MAX_VIDEO_CHANNEL_NUM; k=k+1 ))
do
for (( i=0; i<MAX_STREAM_NUM; i=i+1 ))
do
echo $((i+1+(MAX_STREAM_NUM+1)*k))":"$k":"$i >> $TMP_FILE
done
done


#<video TrackNo="0">
#            <accessname>video1.mjpg</accessname>
#            <sharebuffer>/dev/buff_mgr1</sharebuffer>
#            <fifo>/tmp/venc/c0/command.fifo@0</fifo>
#</video>




channel_num=0
stream_num=1
for (( i=0; i<$((MAX_STREAM_NUM*MAX_VIDEO_CHANNEL_NUM)); i=i+1 ))
do


buff_id=`cat $TMP_FILE |  head -n$((i+1)) | tail -n1 | cut -d":" -f1`
channel_id=`cat $TMP_FILE |  head -n$((i+1)) | tail -n1 | cut -d":" -f2`
encoder_id=`cat $TMP_FILE |  head -n$((i+1)) | tail -n1 | cut -d":" -f3`
if [ $VIDEO_SERVER -eq 1 ];then

	if cat $TARGET_ROOT/../.config | grep -n "CONFIG_JPEG_SNAPSHOT=y"  > /dev/null  2>&1;then
		STR="<video TrackNo=\"$i\">\\n\\t<accessname>video$channel_num-$stream_num.mjpg<\/accessname>\\n\\t<sharebuffer>\/dev\/buff_mgr$((buff_id+i))<\/sharebuffer>\\n\\t<fifo>\/tmp\/venc\/c$channel_id\/command.fifo@$encoder_id<\/fifo>\\n\\t<\/video>\\n\\t"
	else
		STR="<video TrackNo=\"$i\">\\n\\t<accessname>video$channel_num-$stream_num.mjpg<\/accessname>\\n\\t<sharebuffer>\/dev\/buff_mgr$buff_id<\/sharebuffer>\\n\\t<fifo>\/tmp\/venc\/c$channel_id\/command.fifo@$encoder_id<\/fifo>\\n\\t<\/video>\\n\\t"         
	fi
else
	STR="<video TrackNo=\"$i\">\\n\\t<accessname>video$((i+1)).mjpg<\/accessname>\\n\\t<sharebuffer>\/dev\/buff_mgr$buff_id<\/sharebuffer>\\n\\t<fifo>\/tmp\/venc\/c$channel_id\/command.fifo@$encoder_id<\/fifo>\\n\\t<\/video>\\n\\t"         
fi
VIDEO_TRACK_STR=$VIDEO_TRACK_STR""$STR

if [ $VIDEO_SERVER -eq 1 ];then
if [ $(((i+1) % MAX_STREAM_NUM)) -eq 0 ];then

channel_num=$((channel_num+1))
stream_num=1

else 

stream_num=$((stream_num+1))

fi
fi

done

if [ -e $TMP_FILE ];then

rm -f $TMP_FILE

fi

sed -i "s/<server_push>##/<server_push>$VIDEO_TRACK_STR/g"  $TARGET_ROOT/etc/conf.d/serverpush_conf.xml


#<total_num>8</total_num>
#		<stream no="0">
#			<accessname>live0-1.sdp</accessname>			
#			<videotrack>0</videotrack>
#			<audiotrack>-1</audiotrack>			
#			<mdatatrack>-1</mdatatrack>
#		</stream>





