#!/bin/bash
# This script will build expat. 
# It will also copy the header files and the library to the current directory
# in a VN conventional way, i.e., ./lib and ./src. 
PATH=/usr/bin:/bin:$PATH
APP_NAME=sdmgr
PACKAGE_DIR=app
UNTAR_ARG='-jxf'
HOST='arm-linux-'
CC=${HOST}gcc

# check if you have the proper gcc
which $CC > /dev/null || exit 1 

#tar $UNTAR_ARG $TARBALL

[ -d "$PACKAGE_DIR" ] || exit 1

cd $PACKAGE_DIR

# configure it for $HOST
#[ -f "Makefile" ] || ./configure --host=${HOST%-} &> /dev/null

# simply make it
#make --quiet MAKEFLAGS= 
MAKEFLAGS=
make --quiet

cd - > /dev/null


# if i have the shared stripped library and it is newer than the original one, 
# ignore it. 
${HOST}strip -o ${APP_NAME} $PACKAGE_DIR/${APP_NAME}

