/*
 *******************************************************************************
 * $Header: $
 *
 *  Copyright (c) 2007-2010 VN Inc. All rights reserved.
 *
 *  +-----------------------------------------------------------------+
 *  | THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY ONLY BE USED |
 *  | AND COPIED IN ACCORDANCE WITH THE TERMS AND CONDITIONS OF SUCH  |
 *  | A LICENSE AND WITH THE INCLUSION OF THE THIS COPY RIGHT NOTICE. |
 *  | THIS SOFTWARE OR ANY OTHER COPIES OF THIS SOFTWARE MAY NOT BE   |
 *  | PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY OTHER PERSON. THE   |
 *  | OWNERSHIP AND TITLE OF THIS SOFTWARE IS NOT TRANSFERRED.        |
 *  |                                                                 |
 *  | THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE WITHOUT   |
 *  | ANY PRIOR NOTICE AND SHOULD NOT BE CONSTRUED AS A COMMITMENT BY |
 *  | VN INC.                                                     |
 *  +-----------------------------------------------------------------+
 *
 * $History: $
 * 
 *******************************************************************************
 */

/*!
 *******************************************************************************
 * Copyright (c) 2007-2010 VN Inc. All rights reserved.
 *
 * \file
 * sysmgr_network.c
 *
 * \brief
 * Cerberus system manager : modify network interface and http port settings
 *
 * \date
 * 2006/09/20
 *
 * \author
 * Rey Cheng
 *
 *
 *******************************************************************************
 */

#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <linux/reboot.h>
#include <stdlib.h>
#include "xmlmgr.h"

#define NETWORK_INTERFACES_FILE		"/etc/network/interfaces"
#define NETWORK_XML_CONFIG			"/etc/network/network_conf.xml"
#define PPPoE_PAP_SEC				"/etc/ppp/pap-secrets"
#define PPP_PEER					"/etc/ppp/peers/ppp0"

#define NET_TYPE_PPPOE				0
#define NET_TYPE_STATIC				1
#define NET_TYPE_DHCP				2



SCODE set_pppoe(char *szUser, char *szPass)
{
	FILE *fpPPPoESec;
	FILE *fpPPPConf;
	fpPPPoESec = fopen(PPPoE_PAP_SEC, "w");
	fpPPPConf = fopen(PPP_PEER, "w");
	if ((fpPPPoESec != NULL) && (fpPPPConf != NULL)) {
		fprintf(fpPPPoESec, "# Generated by sysmgr\n");
		fprintf(fpPPPoESec, "\"%s\"\t*\t\"%s\"\t*\n", szUser, szPass);
		fclose(fpPPPoESec);
		fprintf(fpPPPConf, "# Generated by sysmgr\n");
		fprintf(fpPPPConf, "noipdefault\ndefaultroute\nusepeerdns\nreplacedefaultroute\nhide-password\nplugin rp-pppoe.so eth0\nuser \"%s\"\n", szUser);
		fclose(fpPPPConf);
		return S_OK;
	} else {
		if (fpPPPoESec != NULL) {
			fclose(fpPPPoESec);
		}
		if (fpPPPConf != NULL) {
			fclose(fpPPPConf);
		}
		return S_FAIL;
	}
	return S_OK;
}

SCODE write_netif(DWORD dwNetType, HANDLE hXMLObject)
{
	FILE *fpNetIf;
	char *pri_nameserver=XmlMgr_GetConfValue(hXMLObject, "/root/network_config/pri_nameserver");
	char *sec_nameserver=XmlMgr_GetConfValue(hXMLObject, "/root/network_config/sec_nameserver");
	

	if ((fpNetIf = fopen(NETWORK_INTERFACES_FILE, "w")) == NULL)
	{
		return S_FAIL;
	}
	// write loopback device
	fprintf(fpNetIf, "auto lo\niface lo inet loopback\n\n");
	if (dwNetType == NET_TYPE_PPPOE)
	{
		fprintf(fpNetIf, "auto ppp0\n");
		fprintf(fpNetIf, "iface ppp0 inet ppp\n");
		fprintf(fpNetIf, "    provider ppp0\n");
	}
	else if (dwNetType == NET_TYPE_STATIC)
	{
		fprintf(fpNetIf, "auto eth0\n");
		fprintf(fpNetIf, "iface eth0 inet static\n");
		fprintf(fpNetIf, "    address %s\n", XmlMgr_GetConfValue(hXMLObject, "/root/network_config/ip_addr"));
		fprintf(fpNetIf, "    netmask %s\n", XmlMgr_GetConfValue(hXMLObject, "/root/network_config/subnet_mask"));
		fprintf(fpNetIf, "    gateway %s\n", XmlMgr_GetConfValue(hXMLObject, "/root/network_config/gateway"));

				
		if (strncmp (pri_nameserver, "", strlen(pri_nameserver))!=0 && strncmp (sec_nameserver, "", strlen(sec_nameserver))!=0 )
		{
			fprintf(fpNetIf, "    up      /usr/sbin/setdns %s %s\n", 
				pri_nameserver, 
				sec_nameserver);
		}else if (strncmp (pri_nameserver, "", strlen(pri_nameserver))!=0 && strncmp (sec_nameserver, "", strlen(sec_nameserver))==0 )
		{
				fprintf(fpNetIf, "    up      /usr/sbin/setdns  %s\n", 
				pri_nameserver);
		}else if (strncmp (pri_nameserver, "", strlen(pri_nameserver))==0 && strncmp (sec_nameserver, "", strlen(sec_nameserver))!=0 )
		{
				fprintf(fpNetIf, "    up      /usr/sbin/setdns  %s\n", 
				sec_nameserver);
		}
		fprintf(fpNetIf, "    up      /usr/sbin/parsenetif eth0\n");
		fprintf(fpNetIf, "\n");
#if 0
		fprintf(fpNetIf, "auto wlan0\n");
		fprintf(fpNetIf, "iface wlan0 inet static\n");
		fprintf(fpNetIf, "    address %s\n", XmlMgr_GetConfValue(hXMLObject, "/root/network_config/ip_addr"));
		fprintf(fpNetIf, "    netmask %s\n", XmlMgr_GetConfValue(hXMLObject, "/root/network_config/subnet_mask"));
		fprintf(fpNetIf, "    gateway %s\n", XmlMgr_GetConfValue(hXMLObject, "/root/network_config/gateway"));
		if (strncmp (pri_nameserver, "", strlen(pri_nameserver))!=0 && strncmp (sec_nameserver, "", strlen(sec_nameserver))!=0 )
		{
			fprintf(fpNetIf, "    up      /usr/sbin/setdns %s %s\n", 
				pri_nameserver, 
				sec_nameserver);
		}else if (strncmp (pri_nameserver, "", strlen(pri_nameserver))!=0 && strncmp (sec_nameserver, "", strlen(sec_nameserver))==0 )
		{
				fprintf(fpNetIf, "    up      /usr/sbin/setdns  %s\n", 
				pri_nameserver);
		}else if (strncmp (pri_nameserver, "", strlen(pri_nameserver))==0 && strncmp (sec_nameserver, "", strlen(sec_nameserver))!=0 )
		{
				fprintf(fpNetIf, "    up      /usr/sbin/setdns  %s\n", 
				sec_nameserver);
		}
		fprintf(fpNetIf, "    up      /usr/sbin/parsenetif wlan0\n");
		fprintf(fpNetIf, "    pre-up  /usr/bin/config-wlan wlan0\n");
#endif
	}
	else // dhcp
	{
		fprintf(fpNetIf, "auto eth0\n");
		fprintf(fpNetIf, "iface eth0 inet dhcp\n");
		fprintf(fpNetIf, "\n");
#if 0
		fprintf(fpNetIf, "auto wlan0\n");
		fprintf(fpNetIf, "iface wlan0 inet dhcp\n");
#endif
	}
	fprintf(fpNetIf, "\n");
	fclose(fpNetIf);
	return S_OK;
}

typedef enum network_behavior_type{
    eNetReboot = 1,
    eNetRestart,
		eNetDoNothing
} ENetBehaviorType;

SCODE sysmgr_set_network(char *szParam)
{
	char *tok;
	char *szConf, *szPreType;
	HANDLE hXMLObject;
    HANDLE hXMLMgr2KeepPreSet;
    ENetBehaviorType eCase;
    
	TXmlMgrInitOptions tXmlMgrInitOpt;
	/* check ending '$', szBuf[ret-1]='\n', szBuf[ret]='\0' */
	if (szParam[strlen(szParam)-2] != '$')
	{
		return S_FAIL;
	}
	// CMD_NETWORK_CONF
	tok = (char *) strtok(szParam, " ");
	// temporal XML configuration file
	tok = (char *) strtok(NULL, " ");

    // get the previous net_type setting
    {
    	tXmlMgrInitOpt.dwVersion = XMLMGR_VERSION;
    	if (XmlMgr_Initial(&hXMLMgr2KeepPreSet, &tXmlMgrInitOpt) != S_OK) {
    		fprintf(stderr, "Initial fail\n");
    		return S_FAIL;
    	}
    
    	if (XmlMgr_ReadFile(hXMLMgr2KeepPreSet, NETWORK_XML_CONFIG) != S_OK) {
    		fprintf(stderr, "Open XML file %s fail\n", NETWORK_XML_CONFIG);
    		return S_FAIL;
    	}

	    szPreType = XmlMgr_GetConfValue(hXMLMgr2KeepPreSet, "/root/network_config/net_type");
    }

	// use xmlmgr to parse the file, initial
	tXmlMgrInitOpt.dwVersion = XMLMGR_VERSION;
	if (XmlMgr_Initial(&hXMLObject, &tXmlMgrInitOpt) != S_OK)
	{
		fprintf(stderr, "Initial fail\n");
		return S_FAIL;
	}

    /* read file */
   	if (XmlMgr_ReadFile(hXMLObject, tok) != S_OK) {
   		fprintf(stderr, "Open XML file %s fail\n", tok);
   		return S_FAIL;
   	}

	/* write to NETWORK_XML_CONFIG */
	if (XmlMgr_WriteFile(hXMLObject, NETWORK_XML_CONFIG) != S_OK)
	{
		fprintf(stderr, "Write to %s fail\n", NETWORK_XML_CONFIG);
		return S_FAIL;
	}
	// setup lo
	szConf = XmlMgr_GetConfValue(hXMLObject, "/root/network_config/net_type");
    
	if (!strcmp(szConf, "pppoe"))
	{
		// PPPoE
		if (set_pppoe(XmlMgr_GetConfValue(hXMLObject, "/root/network_config/pppoe/username"),
								XmlMgr_GetConfValue(hXMLObject, "/root/network_config/pppoe/password")) != S_OK)
		{
			return S_FAIL;
		}
		if (write_netif(NET_TYPE_PPPOE, hXMLObject) != S_OK)
		{
			return S_FAIL;
		}
	}
	else
	{
		// setup eth0
		if (!strcmp(szConf, "dhcp"))
		{
			write_netif(NET_TYPE_DHCP, hXMLObject);
		}
		else if (!strcmp(szConf, "static"))
		{
			write_netif(NET_TYPE_STATIC, hXMLObject);
		}
	}

	// the network setting is re-configured, reboot the system
//	reboot(LINUX_REBOOT_CMD_RESTART);

    if (!strcmp(szPreType, "pppoe") || !strcmp(szConf, "pppoe")) {
        eCase = eNetReboot;
		} else if (!strcmp(szPreType, "dhcp") && !strcmp(szConf, "dhcp")) {
				eCase = eNetDoNothing;
    } else {
        eCase = eNetRestart;
    }

    XmlMgr_Release(&hXMLMgr2KeepPreSet);
	XmlMgr_Release(&hXMLObject);
	unlink(tok);

    if (eCase == eNetReboot) {
				unlink("/etc/resolv.conf");
        sync();
        system("/usr/sbin/reboot");        
		} else if (eCase == eNetRestart) {
				unlink("/etc/resolv.conf");
        system("/etc/init.d/network restart");
    }

	return S_OK;
}
