################################################
# Generated by Code Generator Version 4.2.0.2 #
################################################
MODNAME="vma_ibpe"

rmmod vma_ibpe

rm /dev/$MODNAME

insmod vma_ibpe.ko

MAJOR=`cat /proc/devices | grep $MODNAME | sed -e 's/vma_ibpe//' | sed -e 's/ //'`

if test -z $MAJOR; then
	echo "The device specified is not found !"
else
	echo "Let's make a node here for $MODNAME with major number $MAJOR"
	mknod /dev/$MODNAME c $MAJOR 0
fi
