#!/bin/bash
# This script will untar a ppp tarball from Debian, patch it, and build it. 
PATH=/usr/bin:/bin:$PATH
APP_NAME=inadyn
VERSION=1.96
DEB_ORIG_TARBALL=${APP_NAME}_${VERSION}.orig.tar.gz
DEB_PATCH=${APP_NAME}_${VERSION}-1.diff.gz
PACKAGE_DIR=$APP_NAME-$VERSION
UNTAR_ARG='-zxf'
HOST='arm-linux'
CC=$HOST-gcc
PKG_ROOT=${PWD}

# check if you have proper gcc
which $CC > /dev/null || exit 1

# untar the tarball
tar $UNTAR_ARG $DEB_ORIG_TARBALL

cd $PACKAGE_DIR

# apply Debian's patchs
gunzip -c ${PKG_ROOT}/$DEB_PATCH | patch -p1 --silent

# apply VN's patch
patch -p1 --silent << "INADYN_MAKEFILE"
diff -Nur inadyn-1.96.orig/makefile inadyn-1.96/makefile
--- inadyn-1.96.orig/makefile	2005-10-15 19:12:13.000000000 +0800
+++ inadyn-1.96/makefile	2009-04-29 15:11:16.000000000 +0800
@@ -33,8 +33,8 @@
 	$(OUTDIR)/os_unix.o $(OUTDIR)/os_windows.o $(OUTDIR)/tcp.o $(OUTDIR)/inadyn_cmd.o
 OBJ=$(COMMON_OBJ) $(CFG_OBJ)
 
-COMPILE=gcc  -Wall  -pedantic -c  $(ARCH_SPECIFIC_CFLAGS) $(CFLAGS) -o "$(OUTDIR)/$(*F).o" $(CFG_INC) "$<"
-LINK=gcc $(CFLAGS) -o "$(OUTFILE)" $(OBJ) $(CFG_LIB) $(ARCH_SPECIFIC_LIBS)
+COMPILE=$(CC)  -Wall  -pedantic -c  $(ARCH_SPECIFIC_CFLAGS) $(CFLAGS) -o "$(OUTDIR)/$(*F).o" $(CFG_INC) "$<"
+LINK=$(CC) $(CFLAGS) -o "$(OUTFILE)" $(OBJ) $(CFG_LIB) $(ARCH_SPECIFIC_LIBS)
 
 # Pattern rules
 $(OUTDIR)/%.o : $(SRCDIR)/%.c
INADYN_MAKEFILE

# simply make it
make CC=$HOST-gcc --quiet

cd $PKG_ROOT

#cp -dR $PACKAGE_DIR/bin/linux/inadyn inadyn
#$HOST-strip inadyn

# if i have the shared stripped library and it is newer than the original one,
# ignore it.
[ -f "${APP_NAME}" ] && [ "${PACKAGE_DIR}/bin/linux/${APP_NAME}" -ot "${APP_NAME}" ] && exit 0

${HOST}-strip -o ${APP_NAME} ${PACKAGE_DIR}/bin/linux/${APP_NAME}

