#ifndef __MOZART_AUTOBURN_H__
#define __MOZART_AUTOBURN_H__

// AUTO BURN Part
#define AUTOBURN_SDADDR    0x200000 //4096
#define AUTOBURN_DRAMADDR  0xa00000
#define AUTOBURN_DATASIZE  0x800000 //8MB

#define AUTOBURN_SPIFLASH  0
#define AUTOBURN_NANDFLASH 1
#define AUTOBURN_FLASHTYPE AUTOBURN_SPIFLASH
#define AUTOBURN_FLASHADDR 0x0

#endif

