#
# Makefile for the linux kernel.
#

# Object file lists.

obj-y					:= arch.o int.o time.o debug.o dma.o lm.o devs.o dev_gmac.o
obj-$(CONFIG_MOZART_GPIO)       += gpio.o
obj-$(CONFIG_MOZART_AGPO)       += agpo.o
obj-$(CONFIG_PCI)			+= pci.o pci_regs.o
