#!/bin/sh

FLASH_PATH="/mnt/flash"
FILE="/usr/local/firmware/default_flashfs_files.tar.gz"

if mountpoint /etc
then
	umount /etc
fi

cd $FLASH_PATH
cp  $FLASH_PATH/etc/network/network_conf.xml $FLASH_PATH
cp  $FLASH_PATH/etc/network/interfaces $FLASH_PATH
sync
rm -rf $FLASH_PATH/etc/*
tar -zxf $FILE
mv  $FLASH_PATH/network_conf.xml  $FLASH_PATH/etc/network/
mv  $FLASH_PATH/interfaces $FLASH_PATH/etc/network/
sync
