################################################
# Generated by Code Generator Version 4.2.0.6 #
################################################
MODNAME="vma_jebe"

rmmod vma_jebe

rm /dev/$MODNAME

insmod vma_jebe.ko

MAJOR=`cat /proc/devices | grep $MODNAME | sed -e 's/vma_jebe//' | sed -e 's/ //'`

if test -z $MAJOR; then
	echo "The device specified is not found !"
else
	echo "Let's make a node here for $MODNAME with major number $MAJOR"
	mknod /dev/$MODNAME c $MAJOR 0
fi
