################################################
# Generated by Code Generator Version 3.0.0.0 #
################################################
MODNAME="vpl_vic"

rmmod vpl_vic

#rm /dev/$MODNAME
rm /dev/${MODNAME}0
rm /dev/${MODNAME}1
rm /dev/${MODNAME}2
rm /dev/${MODNAME}3
rm /dev/${MODNAME}4
rm /dev/${MODNAME}5
rm /dev/${MODNAME}6
rm /dev/${MODNAME}7

insmod vpl_vic.ko bAEEn=1 bIrisEn=0 bAFEn=0 bAWBEn=1 bIICSyncVsyncFallingEn=0 dwIrisCtlType=0 gsdwBusFreq=200000000 gsdwSignalWaitTime=4000 > /dev/null 2>&1


MAJOR=`cat /proc/devices | grep $MODNAME | sed -e 's/vpl_vic//' | sed -e 's/ //'`

if test -z $MAJOR; then
	echo "The device specified is not found !"
else
    echo "Let's make a node here for $MODNAME with major number $MAJOR"
    #mknod /dev/$MODNAME c $MAJOR 0
    mknod /dev/${MODNAME}0 c $MAJOR 0
    mknod /dev/${MODNAME}1 c $MAJOR 1
    mknod /dev/${MODNAME}2 c $MAJOR 2
    mknod /dev/${MODNAME}3 c $MAJOR 3
    mknod /dev/${MODNAME}4 c $MAJOR 4
    mknod /dev/${MODNAME}5 c $MAJOR 5
    mknod /dev/${MODNAME}6 c $MAJOR 6
    mknod /dev/${MODNAME}7 c $MAJOR 7
fi
